In [1]:
# load all image from output folder and predict
import os
import numpy as np
import pandas as pd
import cv2
import onnxruntime as ort

In [12]:
def run(foldername):

    # load all images in a directory
    ort_session = ort.InferenceSession("ptfull_24.onnx")
    
    loaded_images = []
    for filename in os.listdir(foldername):
        img = cv2.imread(f'{foldername}/{filename}', cv2.IMREAD_GRAYSCALE)
        # scale pixel values to [0, 1]
        img = img.astype('float32')
        img = img / 255.0
        img = img.reshape(1, 128, 128)
        # store
        loaded_images.append(img)

    # create a numpy array
    loaded_images = np.stack(loaded_images)

    # predict
    ort_inputs = {ort_session.get_inputs()[0].name: loaded_images}
    yhat = ort_session.run(None, ort_inputs)[0]

    # convert to labels
    labels = np.argmax(yhat, axis=1)
    # print labels
    print(labels)
    # print frequency of each label in separated lines
    arr_rs = np.unique(labels, return_counts=True)
    print('---------------------------------')
    for i in range(len(arr_rs[0])):
        print(arr_rs[0][i], " - ", arr_rs[1][i])
    
  
        


In [13]:
# read all folders in img folder
for foldername in os.listdir('img'):
    print(foldername)
    run(f'img/{foldername}')
    print('****************************************************************************************')


25_1
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
---------------------------------
0  -  17
1  -  2
****************************************************************************************
30_2_24
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
---------------------------------
0  -  60
1  -  1
****************************************************************************************
25_2
[4 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0]
---------------------------------
0  -  18
1  -  4
4  -  1
****************************************************************************************
33_1
[0 0 0 0 0 1 1 1 0 1 0 1 0 1 1 1 1 1 0 0 1 1 1 0 1 4 0 0 0 0 0 1 1]
---------------------------------
0  -  16
1  -  16
4  -  1
****************************************************************************************
33_2
[1 1 1 0 0 0 0 0 1 0 0 0 1 0 1 1 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0]
---------------------------------
0  -  23
1