In [4]:
# load all image from output folder and predict
import os
from tensorflow.keras.preprocessing.image import load_img
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import load_model
import numpy as np
import pandas as pd

# load model
model = load_model('model3_24_6_classes.h5', compile=False)
model.compile()

In [5]:
def run(foldername):

    # load all images in a directory
    loaded_images = list()
    for filename in os.listdir(foldername):
        # load image
        img = load_img(foldername + '/' + filename, color_mode="grayscale",
                       target_size=(128, 128))
        # convert to array
        img = img_to_array(img)
        # scale pixel values to [0, 1]
        img = img.astype('float32')
        img = img / 255.0
        # store
        loaded_images.append(img)

    # create a numpy array
    loaded_images = np.asarray(loaded_images)

    # predict
    yhat = model.predict(loaded_images)

    # convert to labels
    labels = np.argmax(yhat, axis=1)
    # print labels
    print(labels)
    # print frequency of each label in separated lines
    arr_rs = np.unique(labels, return_counts=True)
    print('---------------------------------')
    for i in range(len(arr_rs[0])):
        print(arr_rs[0][i], " - ", arr_rs[1][i])
    
  
        


In [6]:
# read all folders in img folder
for foldername in os.listdir('img'):
    print(foldername)
    run('img/' + foldername)
    print('****************************************************************************************')


25_1
1/1 [==============================] - 0s 71ms/step
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
---------------------------------
0  -  17
1  -  2
****************************************************************************************
30_2_24
2/2 [==============================] - 0s 7ms/step
[0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 4 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0
 0 0 0 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 0 1 0 1 0 0]
---------------------------------
0  -  45
1  -  15
4  -  1
****************************************************************************************
25_2
1/1 [==============================] - 0s 20ms/step
[0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0]
---------------------------------
0  -  17
1  -  6
****************************************************************************************
33_1
2/2 [==============================] - 0s 7ms/step
[0 0 0 0 0 4 0 1 4 1 0 1 0 4 4 4 1 1 0 0 1 4 4 0 0 0 0 1 1 0 1 0 0]
---------------------------------
0  -  17
1  -  9
4  -  7
**